Upgrade dependencies and add tests
MandarinConLaBarba/envok pull request #1
Opened 2024-03-04 14:12 UTC by shubham1556

2024-03-05 10:53 UTC, HimanshuGCvent approved these changes

2024-03-05 14:52 UTC, MandarinConLaBarba commented on .tool-versions
Let's take this out

2024-03-05 14:52 UTC, MandarinConLaBarba commented on .gitignore
Let's take this out

2024-03-05 14:53 UTC, MandarinConLaBarba commented on pnpm-lock.yaml
Let's take this out

2024-03-05 14:56 UTC, MandarinConLaBarba requested changes
See inline comments

2024-03-06 17:12 UTC, MandarinConLaBarba approved these changes

2024-03-07 15:24 UTC, merged